baseurl = "http://107.170.11.185/en"
languageCode = "en-us"
title = "Be a Computer Scientist for a Week"
englishurl = "http://107.170.11.185/en"
frenchurl = "http://107.170.11.185/fr"

[params]

	name = "Calem Bendell"
	description = "McGill Be a Computer Scientist for a Week Summer Camp 2016"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Be a Computer Scientist"

		[params.navigation.links]
			about     = "About the Camp"
			services  = "Important Information"
			portfolio = "Camp Streams"
			contact   = "Registration"
      sponsors  = "Sponsors"


	# Hero section
	[params.hero]
		slogan     = "Learn Programming and Problem Solving Skills Early"
		subtitle   = "Learn basic coding and problem solving skills in a week through either games programming, medical computing, weather modelling, or robotics.  It's our pleasure to bring you the 11th year of the *Be a Computer Scientist* camp from June 27 to June 30 during the day."
		buttonText = "Explore the Camp"


	# About section
	[params.about]
		headline    = "Join us for a great learning experience!"
		description = """
Have you ever been puzzled by science? Have you tried to analyze exactly how a computer works? Are you good at problem solving, trouble-shooting, and coming up with original solutions? When people ask you about how many languages you are familiar with, do you answer: "Three. English, French and Java? Then the place you want to be, from June 27 to June 30 2016, is at McGill University's "Be A Computer Scientist for a Week"!

Students from high schools will be given the opportunity to live out their passion, and learn more about the intricate sides of Computer Science! The name "computer science", or CS for short, might give the impression that we are trying to study computers, the every day machines we use for e-mail, chatting and watching movies. But CS is not about surfing the net, making charts with Excel and writing programs. Dijkstra, a famous computer scientist, once said: "Computer science is no more about computers than astronomy is about telescopes."

Instead, CS is the theoretical study of computing systems and information. It deals with design principles, requirements analysis, and implementation of hardware or software to solve problems in biology, physics, pharmacy or economy. It is the study of algorithms and of methods for analyzing, testing and verifying concepts. To sum it all up, Computer Science offers you skills that can be applied to any discipline and help you solve the "problems of the future"!
"""

	# Service section
	[params.services]
		headline = "Important Information"

        [[params.services.list]]
            icon = ""
            title = "The Basics"
            description = """ "Be A Computer Scientist for a Week" is a free but intensive day camp on the McGill University campus, in the heart of downtown.
            This year we offer four themes: Games Programming, Robotics, Medical Computing, Climate Modelling.
            Students will first be given simple programming assignments, which will progressively become complex. By the end of the camp, students will have completed a project in their field. """

        [[params.services.list]]
			icon = ""
			title = "Applicants"
			description = "Applicants should have strong math, science and other computer related skills, the ability to work well with others, and a serious interest in participation.  Applicants should further have sponsorship from a teacher that should send a short sponsorship note to the conact email below."

		[[params.services.list]]
            icon = ""
            title = "In the Mornings"
            description = "The morning units will begin with a special keynote speaker. This will either be a professor from McGill or some external visiting speaker. The keynote speaker will present the theme for the day using an audiovisual presentation and talk. The purpose of the talk will be to inform and cause excitement. After this the students will continue with a classroom lesson focused on the material they will need to acquire for the day."

        [[params.services.list]]
            icon = ""
            title = "In the Afternoons"
            description = "The afternoon units will be organized around the student team. Each group will have 2 to 3 students. The selection of groups will be changed daily to maximize the interaction between students. The groups will be selected randomly. The afternoon will focus on team problem solving. The research group will, as a unit, solve a series of progressively more difficult computer problems within their selected real life domain."

    [[params.services.list]]
      icon = ""
      title = "Downloadable Material"
      description = """NEED TO ADD LINKS TO POSTER AND LETTER HERE"""

  [params.portfolio]
    headline = "Our Camp Streams"

    # Portfolio modals
	[params.portfolio.modal]
        client = ""
        date = ""
        category = ""
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Register!  Or Ask Us Questions"
		description = "Send us an email and we will get back to you as soon as possible!"
		phone = ""
		email = "joseph.vybihal at mail dot mcgill dot ca"

  [params.sponsors]
    headline = "Our Sponsors"
