baseurl = "http://summercamp.cs.mcgill.ca/fr"
languageCode = "fr"
title = "Une semaine de découverte dans les sciences informatiques"

[params]

	name = "Calem Bendell"
	description = "Une semaine de découverte dans les sciences informatiques"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Une semaine de découverte dans les sciences informatiques"

		[params.navigation.links]
			about     = "Informations Camp"
			services  = "Informations Importantes"
			portfolio = "Les Streams Camp"
			contact   = "Enregistrement"
      sponsors  = "Sponsors"


	# Hero section
	[params.hero]
		slogan     = "Apprenez les techniques de programmation et de résolution de problèmes au début"
		subtitle   = "Apprenez les fondements du code informatique et de la résolution de problèmes en une semaine grâce à la programmation de jeux, l'informatique médicale, la modélisation de la météo ou la robotique. C'est notre grand plaisir de vous présenter la 11e édition de la Semaine de découverte des sciences informatiques, un camp de jour qui se tient du 27 au 30 juin."
		buttonText = "Explorez le Camp"


	# About section
	[params.about]
		headline    = "Joignez-vous à nous pour une grande expérience d'apprentissage!"
		description = """Ëtes-vous intrigué-e- par la science? Avez-vous essayé d’analyser comment un ordinateur fonctionne? Êtes vous habile à résoudre des problèmes, à vous dépanner et à trouver des solutions originales? Quand on vous demande combien de langues vous parlez, répondez-vous: “Trois. Anglais, Français et Java”? Si oui, rendez-vous du 27 au 30 juin 2016 à la “Semaine de découverte des sciences informatiques”, organisée par l'Université McGill!

Des élèves d'écoles secondaires de partout à Montréal auront la chance de vivre leur passion et d’en apprendre plus sur les aspects pointilleux de l’informatique! Le nom “informatique” peut donner l’impression qu’on étudie les ordinateurs, les machines qui font partie de notre quotidien pour envoyer des courriels, clavarder ou écouter des films. Mais l’informatique ne se penche pas sur la navigation internet, la création d'histogrammes sur Excel, ou la programmation. Dijkstra, un scientifique et informaticien, a dit: “L’informatique n'a pas plus à voir avec les ordinateurs que l’astronomie avec les téléscopes.” Plutôt, l’informatique est l'étude théorique des systèmes informatiques et de l’information. Elle traite des principes de design, de l’analyse des conditions et de l’application des matériels ou des logiciels informatiques pour résoudre les problèmes posés par la biologie, la physique, la pharmacologie ou l'économie. C’est l'étude d’algorithmes et de méthodes d’analyse, d'examen et de vérification de concepts. En résumé, l'étude de l’informatique vous offrira des habiletés qui pourront vous être utiles dans n’importe quelle discipline et qui vous aideront à résoudre les “problèmes du futur”!
"""

	# Service section
	[params.services]
		headline = "Informations Importantes"

        [[params.services.list]]
            icon = ""
            title = "Les Bases"
            description = """ “La Semaine de découverte des sciences informatiques” est un camp de jour gratuit mais intensif situé sur le campus de l'Université McGill, au cœur du centre-ville. Cette année, nous avons quatre thèmes: la programmation de jeux, la robotique, l'informatique médicale et la modélisation climatique. Les étudiant-e-s se verront assigner de simples exercices de programmation qui deviendront progressivement complexes. À la fin du camp, les étudiant-e-s auront complété un projet dans leur domaine. """

        [[params.services.list]]
			icon = ""
			title = "Applicant-e-s"
			description = "Les applicant-e-s devraient avoir des connaissances solides en mathématiques, en sciences, et dans des domaines reliés aux ordinateurs, la capacité de bien travailler avec les autres, et un intérêt sérieux envers leur participation. Les applicant-e-s devraient également obtenir le parrainage d'un-e professeur-e, qui devrait envoyer un court message de parrainage à l'adresse courriel ci-bas."

		[[params.services.list]]
            icon = ""
            title = "Les matins"
            description = "Un orateur spécial: un professeur de McGill ou un invité spécial de l'extérieur commencera la journée en présentant le thème du jour à l’aide d'une présentation audiovisuelle. Le but du discours est d’informer et de provoquer l’excitation générale. Par la suite, les élèves suivront un cours en classe portant sur la matière qu’ils auront à acquérir cette journée-ci."

        [[params.services.list]]
            icon = ""
            title = "L'après-midi"
            description = "Les sessions d’après-midi seront organisées autour de “Groupes de Recherche”. Chaque groupe comprendra de 2 à 3 étudiant-e-s. La composition des groupes sera changée tous les jours pour maximiser l’interaction entre les étudiant-e-s. Les groupes seront choisis au hasard. L’après-midi se concentrera sur la résolution de problèmes en équipe. Le groupe de recherche résoudra, en équipe, une série de problèmes d’informatique qui augmenteront chaque jour en difficulté."

  [params.portfolio]
    headline = "Nos quatre thèmes"

	[params.portfolio.modal]
        client = ""
        date = ""
        category = ""
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Enregistrement"
		description = "Inscrivez-vous! Ou posez-nous vos questions. Envoyez-nous un courriel et nous vous répondrons dès que possible!"
		phone = ""
		email = "joseph.vybihal at mail dot mcgill dot ca"

  [params.sponsors]
    headline = "Nos partenaires"
